from pydantic import BaseModel, Field
from typing import List 

class ProtagonistProfile(BaseModel):
    core_trait: str
    primary_goal: str

class Episode(BaseModel):
    episode_number: int
    title: str
    click_title: str
    summary: str
    visual_storyboard: str
    emotion_tag: str
    open_loop: str
    viral_hook: str
    cliffhanger_action: str

class SeriesArc(BaseModel):
    series_title: str
    protagonist_profile: ProtagonistProfile
    episodes: List[Episode]


class NarrativeAnalysis(BaseModel):
    """Schema for the Narrative Intelligence Engine response."""
    episode_title: str
    dominant_emotion: str


class CleanEpisodeResponse(BaseModel):
    """The clean, production-ready schema for a single episode."""
    episode_number: int = Field(description="Sequential episode number.")
    title: str = Field(description="The contextual viral title generated by Narrative Intelligence.")
    viral_hook: str = Field(default="", description="The high-retention opening hook for the episode.")
    summary: str = Field(description="The core narrative arc summary.")
    cliffhanger_action: str = Field(description="The ending hook action.")
    emotion: str = Field(description="The true subtextual dominant emotion.")
    cliffhanger_score: float = Field(description="Retention score from 0.0 to 1.0.")
    seo_hashtags: List[str] = Field(description="Extracted high-value hashtags.")
    is_brand_safe: bool = Field(default=True, description="Safety status flag.")
    safety_score: float = Field(default=0.0, description="Toxicity score from model.")


class CleanSeriesResponse(BaseModel):
    """The master JSON payload returned to the frontend."""
    series_title: str
    episodes: List[CleanEpisodeResponse]